"""empty message

Revision ID: ab83b9156fd8
Revises: a1ff2cd86814
Create Date: 2020-12-27 18:44:44.870048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab83b9156fd8'
down_revision = 'a1ff2cd86814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('description', sa.String(length=400), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'description')
    # ### end Alembic commands ###
